Repository redhat-appstudio/docs.appstudio.io, pull requests merged in 2023-08, with the labels that each got.

#183 Updates screenshots, link, and copy in GS guide.
  docs/modules/.DS_Store
  docs/modules/ROOT/.DS_Store
  docs/modules/ROOT/images/.DS_Store
  docs/modules/ROOT/images/Environments.png
  docs/modules/ROOT/images/Pipeline-runs.png
  docs/modules/ROOT/pages/getting-started/get-started.adoc
Labels: size: S

#185 Add section about data injection
  docs/modules/ROOT/pages/how-to-guides/testing_applications/proc_creating_custom_test.adoc
Labels: size: M

#186 Fixes explanation of temporary environments in step 7
  docs/modules/ROOT/pages/how-to-guides/testing_applications/proc_adding_an_integration_test.adoc
Labels: size: XS

#188 Fixes bash commands in steps 2 and 3
  docs/modules/ROOT/pages/how-to-guides/Secure-your-supply-chain/proc_inspect-slsa-provenance.adoc
Labels: size: S
