Repository redhat-appstudio/docs.appstudio.io, pull requests merged in 2023-11, with the labels that each got.

#205 Update the docs to match the current state of JBS
  docs/modules/ROOT/pages/how-to-guides/Secure-your-supply-chain/proc_java_dependencies.adoc
Labels: size: XL

#214 HACDOCS-588
  docs/modules/ROOT/nav-how-to-guides.adoc
  docs/modules/ROOT/pages/how-to-guides/configuring-builds/proc_preventing_redundant_rebuilds.adoc
Labels: size: XL

#212 HACDOCS-488: Updating Important notices upstream topic
  docs/modules/ROOT/pages/support/data-privacy.adoc
Labels: documentation, Needs SME review, size: S

#218 HACDOCS-478-FIX: To resolve merge conflicts in original HACDOCS-478 branch.
  docs/modules/ROOT/pages/getting-started/roles_permissions.adoc
Labels: size: XS, size: M

#217 User-initiated application cloning
  docs/modules/ROOT/pages/how-to-guides/managing-applications/proc-managing_applications.adoc
Labels: size: XL
