Repository redhat-appstudio/docs.appstudio.io, pull requests merged in 2023-09, with the labels that each got.

#192 Add link to roles and permissions Hacdocs 556
  docs/modules/ROOT/pages/getting-started/get-started.adoc
Labels: size: S

#194 HACDOCS-509: Adding info about secrets to the Privacy notice
  docs/modules/ROOT/pages/support/data-privacy.adoc
Labels: documentation, size: S

#198 Updated the content for clarity
  docs/modules/ROOT/pages/how-to-guides/proc_hermetic-builds.adoc
  docs/modules/ROOT/pages/how-to-guides/proc_prefetching-dependencies-to-support-hermetic-build.adoc
Labels: size: S

#193 FBC Documentation
  docs/modules/ROOT/pages/how-to-guides/proc_maintaining_operator_graphs.adoc
  package-lock.json
Labels: size: XXL
