Repository redhat-appstudio/docs.appstudio.io, pull requests merged in 2023-07, with the labels that each got.

#149 Add docs on Automatic JBS Setup
  docs/modules/ROOT/pages/how-to-guides/Secure-your-supply-chain/proc_java_dependencies.adoc
Labels: size: XS

#175 doc edits to dev PR and modularization changes
  docs/modules/ROOT/pages/how-to-guides/Secure-your-supply-chain/proc_java_dependencies.adoc
Labels: documentation, size: XS

#181 Updates adding integration test doc
  docs/modules/ROOT/pages/how-to-guides/testing_applications/proc_adding_an_integration_test.adoc
Labels: size: XS

#180 STONEBLD-1494: Add procedure to update buildah task
  docs/modules/ROOT/pages/how-to-guides/configuring-builds/proc_customize_build_pipeline.adoc
Labels: size: XS, size: M

#184 Update step #5 per HACBS-2307
  docs/modules/ROOT/pages/how-to-guides/proc_managing-compliance-with-the-enterprise-contract.adoc
Labels: size: XS
