Repository redhat-appstudio/docs.appstudio.io, pull requests merged in 2023-10, with the labels that each got.

#202 Update proc_managing-compliance-with-the-enterprise-contract.adoc
  docs/modules/ROOT/pages/how-to-guides/proc_managing-compliance-with-the-enterprise-contract.adoc
Labels: size: S

#197 RHTAPBUGS-581: Added a sample custom task
  docs/modules/ROOT/pages/how-to-guides/configuring-builds/proc_customize_build_pipeline.adoc
Labels: size: XS, size: XL

#199 Revise doc; include new example kubeconfig
  docs/modules/ROOT/pages/how-to-guides/managing-environments/proc_creating_your_own_environment.adoc
Labels: size: XL

#203 integration tests: Add warning about not specifying environment
  docs/modules/ROOT/pages/how-to-guides/testing_applications/proc_adding_an_integration_test.adoc
Labels: size: XS

#207 Update proc_inspect-slsa-provenance.adoc
  docs/modules/ROOT/pages/how-to-guides/Secure-your-supply-chain/proc_inspect-slsa-provenance.adoc
Labels: size: XS

#195 HACDOCS-508: Update Importing and configuring topic for secrets
  docs/modules/ROOT/pages/how-to-guides/Import-code/proc_importing_code.adoc
Labels: size: XS

#210 HACDOCS-630: Updated Add secret upstream content to match UI
  docs/modules/ROOT/pages/how-to-guides/configuring-builds/proc_creating-secrets-for-your-builds.adoc
Labels: documentation, Needs SME review, size: M, WIP

#209 Update proc_creating_custom_test.adoc
  docs/modules/ROOT/pages/how-to-guides/testing_applications/proc_creating_custom_test.adoc
Labels: size: XS

#173 HACDOCS-489: Adding content for importing code from private repo
  docs/modules/ROOT/pages/how-to-guides/Import-code/proc_importing_code.adoc
Labels: documentation, size: XS, size: L, on hold (see comments)
