Repository redhat-appstudio/docs.appstudio.io, pull requests merged in 2023-06, with the labels that each got.

#122 added section for registry base images
  docs/modules/.DS_Store
  docs/modules/ROOT/pages/how-to-guides/Import-code/proc_importing_code.adoc
Labels: documentation

#166 Update proc_importing_code.adoc
  docs/modules/ROOT/pages/how-to-guides/Import-code/proc_importing_code.adoc
Labels: size: XS

#146 Hermetic build documentation
  antora-lunr-ui/css/main.css
  docs/modules/ROOT/images/build-requirements.png
  docs/modules/ROOT/nav-how-to-guides.adoc
  docs/modules/ROOT/pages/how-to-guides/proc_hermetic-builds.adoc
  docs/modules/ROOT/pages/how-to-guides/proc_prefetching-dependencies-to-support-hermetic-build.adoc
  docs/modules/ROOT/pages/partials/con_hermetic_verification.adoc
Labels: size: XS

#126 Glossary grooming
  docs/modules/ROOT/pages/glossary/index.adoc
Labels: size: XS

#174 added doc on creating secrets for builds
  docs/modules/ROOT/nav-how-to-guides.adoc
  docs/modules/ROOT/pages/how-to-guides/configuring-builds/proc_creating-secrets-for-your-builds.adoc
Labels: documentation, size: XS
