Repository redhat-appstudio/docs.appstudio.io, pull requests merged in 2024-05, with the labels that each got.

#250 feat(STONEINTG-837): update org of integration-examples
  docs/modules/ROOT/pages/how-to-guides/testing_applications/proc_creating_custom_test.adoc
Labels: size: XS

#253 chore(RHTAPWATCH-895): add BYO Quay docs
  docs/modules/ROOT/pages/how-to-guides/configuring-builds/proc_customize_build_pipeline.adoc
Labels: size: L, size: M

#251 Update roles to use "admin" role name instead of non existing "owner" role
  docs/modules/ROOT/pages/getting-started/roles_permissions.adoc
  docs/modules/ROOT/pages/how-to-guides/managing-workspaces/proc-creating_a_team_workspace.adoc
Labels: size: S

#255 Explain how to configure Renovate for GitLab
  docs/modules/ROOT/pages/concepts/RenovateBot/index.adoc
Labels: size: XL

#259 Add documentation for using custom additional tags
  docs/modules/ROOT/nav-how-to-guides.adoc
  docs/modules/ROOT/pages/how-to-guides/configuring-builds/proc_custom-tags.adoc
Labels: size: XL

#264 Update apply-tags example
  docs/modules/ROOT/pages/how-to-guides/configuring-builds/proc_custom-tags.adoc
Labels: size: L
