Repository redhat-appstudio/docs.appstudio.io, pull requests merged in 2024-03, with the labels that each got.

#237 How-to guide on retriggering builds
  docs/modules/ROOT/pages/how-to-guides/configuring-builds/proc_retriggering_build_pipelines.adoc
Labels: size: XS, size: XL

#242 Create new Releasing with an advisory doc
  docs/modules/ROOT/nav-how-to-guides.adoc
  docs/modules/ROOT/pages/how-to-guides/proc_release_advisory.adoc
Labels: size: L, size: XL

#245 Update link to CasC template repo
  docs/modules/ROOT/pages/how-to-guides/configuration-as-code/proc_configuration_as_code.adoc
Labels: size: XS

#244 feat(STONEINTG-765): remove outdated info in surface-tests doc
  docs/modules/ROOT/pages/how-to-guides/testing_applications/surface-level_tests.adoc
Labels: size: XL

#200 Add information on PR images expiring
  docs/modules/ROOT/pages/how-to-guides/configuring-builds/proc_upgrade_build_pipeline.adoc
Labels: size: S

#246 Drop unnecessary instruction
  docs/modules/ROOT/pages/how-to-guides/testing_applications/enable_snyk_check_for_a_product.adoc
Labels: size: M
