Repository redhat-appstudio/docs.appstudio.io, pull requests merged in 2024-02, with the labels that each got.

#234 fix(STONEINTG-598): clarify required tests
  docs/modules/ROOT/pages/how-to-guides/testing_applications/proc_adding_an_integration_test.adoc
Labels: size: S

#235 Clean up the top of the secrets how-to-guide
  docs/modules/ROOT/pages/how-to-guides/configuring-builds/proc_creating-secrets-for-your-builds.adoc
Labels: size: XS

#236 doc(stoneintg-756): write how to manually re-trigger integration test
  docs/modules/ROOT/nav-how-to-guides.adoc
  docs/modules/ROOT/pages/how-to-guides/testing_applications/proc_retriggering_integration_tests.adoc
Labels: size: S, size: L, size: M

#201 HACDOCS-558: Update App studio documentation with npm package manager
  docs/modules/ROOT/pages/how-to-guides/proc_hermetic-builds.adoc
  docs/modules/ROOT/pages/how-to-guides/proc_prefetching-dependencies-to-support-hermetic-build.adoc
  docs/modules/ROOT/pages/partials/con_hermetic_troubleshooting.adoc
  docs/modules/ROOT/pages/partials/con_hermetic_verification.adoc
Labels: documentation, Needs SME review, size: L, size: XL, size: XXL, size: M, WIP

#240 Rename the github app name
  docs/modules/ROOT/pages/how-to-guides/configuring-builds/proc_upgrade_build_pipeline.adoc
  docs/modules/ROOT/pages/how-to-guides/proc_maintaining_operator_graphs.adoc
Labels: size: XS

#238 Add Configuration-as-Code documentation and example
  docs/modules/ROOT/nav-how-to-guides.adoc
  docs/modules/ROOT/pages/how-to-guides/configuration-as-code/proc_configuration_as_code.adoc
Labels: size: XXL
