Repository redhat-appstudio/docs.appstudio.io, pull requests merged in 2024-06, with the labels that each got.

#261 Update build-definitions references to new org
  docs/modules/ROOT/pages/how-to-guides/configuring-builds/proc_creating-secrets-for-your-builds.adoc
  docs/modules/ROOT/pages/how-to-guides/proc_hermetic-builds.adoc
  docs/modules/ROOT/pages/how-to-guides/proc_managing-compliance-with-the-enterprise-contract.adoc
Labels: size: S

#270 feat(STONEINTG-926): update snyk token guide
  docs/modules/ROOT/pages/how-to-guides/testing_applications/enable_snyk_check_for_a_product.adoc
Labels: size: M

#271 feat(STONEINTG-892): add proc to create override snapshot
  docs/modules/ROOT/nav-how-to-guides.adoc
  docs/modules/ROOT/pages/how-to-guides/testing_applications/con_test-overview.adoc
  docs/modules/ROOT/pages/how-to-guides/testing_applications/proc_creating_override_snapshot.adoc
Labels: size: XL, size: XXL

#274 feat(STONEINTG-892): update doc for override snapshot
  docs/modules/ROOT/pages/how-to-guides/testing_applications/proc_creating_override_snapshot.adoc
Labels: size: S, size: M
